### ISSUE TITLE
Zoom and JWMMF

### ISSUE THREAD

**Issue by khcarmel** [sircharlo/jw-meeting-media-fetcher#244] opened 2022-04-08 20:51 UTC
when I open zoom jwmmf closes. If i do not open Zoom jwmmf remains open and stable. 

### System specs
- Windows_NT 10.0.19044
- JWMMF v22.4.0

### Anonymized `prefs.json`
```
{
  "autoOpenFolderWhenDone": null,
  "autoQuitWhenDone": null,
  "autoRunAtBoot": true,
  "autoStartSync": null,
  "congServer": null,
  "congServerDir": "",
  "congServerPass": null,
  "congServerPort": null,
  "congServerUser": null,
  "congregationName": "***",
  "enableMediaDisplayButton": true,
  "enableMp4Conversion": null,
  "enableMusicButton": true,
  "enableMusicFadeOut": null,
  "enableVlcPlaylistCreation": null,
  "excludeLffi": true,
  "excludeLffiImages": true,
  "excludeTh": true,
  "keepOriginalsAfterConversion": null,
  "lang": "E",
  "langUpdatedLast": "2022-04-08T18:02:18.316Z",
  "localAdditionalMediaPrompt": true,
  "localAppLang": "en",
  "localOutputPath": "***",
  "maxRes": "720p",
  "musicFadeOutTime": "30",
  "musicFadeOutType": "timer",
  "musicVolume": "100",
  "mwDay": "4",
  "mwStartTime": "12:00",
  "weDay": "6",
  "weStartTime": "22:00"
}
```

**Comment by sircharlo** [comment] 2022-04-09 01:00
I cannot reproduce this behavior, either by launching JWMMF first then Zoom, or the other way around.
Can you document with screenshots or a video?

**Comment by sircharlo** [comment] 2022-04-13 12:35
@khcarmel I will close this issue for now; feel free to reopen it if you have additional information to add!

**Closed by sircharlo** 2022-04-13 12:35 UTC
