### ISSUE TITLE
[BUG] stuck on target meeting screen

### ISSUE THREAD

**Issue by mtdvlpr** [sircharlo/jw-meeting-media-fetcher#153] opened 2021-12-29 18:06 UTC
**Describe the bug**
When downloading the media and auto opening the folders. The media fetcher shows a smiley face with a countdown button. After the countdown stops, the target meeting screen pops up again (Where you can opt to include additional media). Clicking the next button doesn't work. You get the transition from closing and opening again, but it just stays open.

**To Reproduce**
1. Go to 'fetch media'
2. Click on 'next'
3. Try to close the target meeting screen

**Expected behavior**
The screen should close properly

**Logs**
The console shows no errors.

**Screenshots**
If possible, add screenshots to help explain your problem.

**System specs (please complete the following information):**
 - OS: Ubuntu 20
 - App Version v21.12.2

**Additional context**

**Comment by sircharlo** [comment] 2021-12-29 20:50
Hi there @mtdvlpr !
I don't think I can replicate this issue.
Look at this video and let me know if you're doing something different?

https://user-images.githubusercontent.com/1275666/147702408-9e66f2cc-5250-4a15-a59d-4a7289654ad2.mp4

**Comment by mtdvlpr** [comment] 2021-12-29 21:10
Hi @sircharlo, The first time it works, but the second time (when its already downloaded) it breaks.
I have the following setup:
- Ubuntu 20
- v21.12.2
- exclude all th and lffi media
- offer to import additional media
- initiate media sync on app launch
- open folder after media sync

https://user-images.githubusercontent.com/46671786/147703480-9fd9ad4c-cd97-43f2-937b-9db39206d7ce.mp4

**Comment by sircharlo** [comment] 2021-12-30 13:20
I see! Thanks for that video. I was able to reproduce the issue. 
The cause is a simple event bind/unbind oversight on my part. 
Fixed in https://github.com/sircharlo/jw-meeting-media-fetcher/commit/9b48a4be0a12cc8e4fd0919c1f388afa9b84f438, slated for release next month.

**Closed by sircharlo** 2021-12-30 13:20 UTC
Labels: bug

**Comment by mtdvlpr** [comment] 2021-12-30 13:25
Thank you for fixing it so quickly!
